### ISSUE TITLE
where can download the threejs typings defined files?

### ISSUE THREAD

**Issue by dyh333** [chliebel/angular2-3d-demo#1]
hi, @chliebel . i am trying run threejs in angular2 too. but i can not find the threejs or three-trackballcontrols typings defined files in https://www.npmjs.com. where can i download them? thanks

**Comment by christianliebel** [comment]
Hi @dyh333,

the [new way to install declaration files](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) (which my sample currently does not make is of) in TypeScript 2.0 is to use the [scoped `@types` npm packages](https://www.npmjs.com/~types).

For THREE.js, you would just run `npm install @types/three`.

I hope this helps. If so, please close this issue. Thanks.

Best,
Christian

**Comment by dyh333** [comment]
@chliebel . thanks, it works.

**Comment by christianliebel** [comment]
@dyh333 Perfect! Glad to help.
