### ISSUE TITLE
how to import threex lib into angular2

### ISSUE THREAD

**Issue by dyh333** [chliebel/angular2-3d-demo#2]
hi, @chliebel. I am trying to use threex.domEvents lib(https://github.com/jeromeetienne/threex) in angular2 repo, but failed. Because there is no @types in npmjs, so I don't know how to import threex into my ng2 repo. 
Would you have any idea to solve it ? 
thanks very much.

**Comment by christianliebel** [comment]
Hi @dyh333. Indeed, it looks as if there are no typings for THREEx. But that’s no problem, as TypeScript is a superset of JavaScript and thus plain JavaScript continues to work. Simply load the THREEx script you’d like to use (e.g. via a `script` tag) in your `index.html` file.

Your IDE or text editor might show the following warning: `Cannot find name 'THREEx'`

To get around this, create a `global.d.ts` file in your project root containing the following line:

`declare const THREEx: any;`

By doing so, you declare a project-global type named `THREEx`. As it’s assigned the type `any`, you’re opting out of strict typing for this identifier. The downside of this approach is that – depending on your editor – you won’t get any code completion for THREEx functions. Now, you can just use THREEx it in your TypeScript code just as you would in JavaScript:

`const pac = new THREEx.Pacman({…});`

**Comment by dyh333** [comment]
hi, @chliebel . thanks your reply. i have tried it, and it works normal. 
however, i think if not add these three lib just like '<script src="vendor/three.js"></script>' in index.html file would be better. so i tried to use npm to install three lib like 'npm install three --save ; npm install @types/three --save -dev' . and used it in .ts like 'let THREE = require('three'); console.log(THREE) '. it also works. but unfortunately when i test THREEx as this way (install from https://www.npmjs.com/package/threex-domevents), it can not work. 

really thank you, hope learning more from you.
